### ISSUE TITLE
Bug: 3 parallel axes wrist - is there a solution or not?

### ISSUE THREAD

**Issue by JonathanKuelz** [OstermD/EAIK#16]
I have a robot with the following properties:

```
H =
array([
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  0., -1., -1., -1., -1.]
])

P =
Out[14]: 
array([
       [ 0.   ,  0.195,  0.16 ,  0.127,  0.171,  0.206,  0.189],
       [ 0.   ,  0.   ,  0.176,  0.   ,  0.   ,  0.   , -0.   ],
       [ 0.   ,  0.172,  0.   , -0.196, -0.146, -0.206, -0.126]
]) 
```

with the following error behavior (on the python side, but the issue seems to be in the original C++ code):
```
robot.hasKnownDecomposition()
==> True
robot.hasSphericalWrist()
==> False

robot.IK_batched(...)
==>
terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
what():  This manipulator type (Axis 1,2,3 parallel with no additional parallel axes) is not yet solvable by EAIK.
```

There is a mismatch between the "has known decomposition" return and the error in the inverse kinematics. Obviously, axes 1,2,3 are not parallel, but 4,5,6 are. It looks to me as if the original robot doesn't have a known decomposition, but the "inverted chain" might have, but runs in the error message before it can be computed. Could you please check this @OstermD ?

**Comment by OstermD** [comment]
This manipulator poses indeed an issue - the last parallel axis causes our subproblem decomposition for three intermediate axes to break down (SP6 simplifies). We can't decompose it into a three-parallel mechanism that only uses the the last three axes either, as the first two axes would need to intersect in this case.

However, this manipulator is implicitly redundant in every configuration.

Here is an interesting publication with this regard (See Example 4 on page 18 of the pdf):

Geometric Interpretation of Manipulator Singularities by Paden and Sastry:
https://www2.eecs.berkeley.edu/Pubs/TechRpts/1984/378.html


Currently we don't specifically forbid such implicitly redundant manipulators or detect them, but the behavior of our tool is in these cases undefined. 
In some cases we'd probably also yield valid LS solutions (out of the infinite solution space) for such manipulators but this is currently not guaranteed.

Detection of implicit redundancies is something we should probably add in the future.

**Comment by OstermD** [comment]
See #17 for further information
